const patients = [{
    "first_name": "Tessi",
    "last_name": "McTerrelly",
    "email": "tmcterrelly0@weebly.com",
    "sex": "female",
    "blood_type": "O+",
    "address": "00563 Lake View Crossing",
    "city": "Lima",
    "state": "Ohio",
    "birthdate": "1985-03-31T13:00:07Z",
    "zipcode": "45807"
}, {
    "first_name": "Baxie",
    "last_name": "Lunck",
    "email": "blunck1@auda.org.au",
    "sex": "male",
    "blood_type": "O-",
    "address": "96098 Forest Run Drive",
    "city": "Las Vegas",
    "state": "Nevada",
    "birthdate": "1973-03-12T15:41:03Z",
    "zipcode": "89130"
}, {
    "first_name": "Hoyt",
    "last_name": "Andriveaux",
    "email": "handriveaux2@netvibes.com",
    "sex": "male",
    "blood_type": "A-",
    "address": "73446 Texas Street",
    "city": "Denver",
    "state": "Colorado",
    "birthdate": "1938-10-31T12:51:54Z",
    "zipcode": "80255"
}, {
    "first_name": "Ellis",
    "last_name": "Gogin",
    "email": "egogin3@ted.com",
    "sex": "male",
    "blood_type": "A-",
    "address": "7 Rusk Terrace",
    "city": "Raleigh",
    "state": "North Carolina",
    "birthdate": "1949-01-08T13:46:48Z",
    "zipcode": "27626"
}, {
    "first_name": "Karlen",
    "last_name": "Ingry",
    "email": "kingry4@arizona.edu",
    "sex": "female",
    "blood_type": "AB-",
    "address": "03798 Eggendart Circle",
    "city": "Orange",
    "state": "California",
    "birthdate": "1938-02-02T07:21:13Z",
    "zipcode": "92867"
}, {
    "first_name": "Adelice",
    "last_name": "Reubel",
    "email": "areubel5@tumblr.com",
    "sex": "male",
    "blood_type": "A-",
    "address": "1 Northview Avenue",
    "city": "Montgomery",
    "state": "Alabama",
    "birthdate": "1960-03-27T02:03:22Z",
    "zipcode": "36134"
}, {
    "first_name": "Ediva",
    "last_name": "McKeller",
    "email": "emckeller6@freewebs.com",
    "sex": "male",
    "blood_type": "A-",
    "address": "8 Kropf Way",
    "city": "Fargo",
    "state": "North Dakota",
    "birthdate": "1983-04-22T21:16:46Z",
    "zipcode": "58106"
}, {
    "first_name": "Julietta",
    "last_name": "Brame",
    "email": "jbrame7@soup.io",
    "sex": "female",
    "blood_type": "B+",
    "address": "16 Straubel Trail",
    "city": "Jamaica",
    "state": "New York",
    "birthdate": "1960-06-08T06:07:06Z",
    "zipcode": "11431"
}, {
    "first_name": "Franklyn",
    "last_name": "Leathard",
    "email": "fleathard8@bravesites.com",
    "sex": "male",
    "blood_type": "AB-",
    "address": "971 Express Drive",
    "city": "Amarillo",
    "state": "Texas",
    "birthdate": "1993-10-19T01:45:40Z",
    "zipcode": "79165"
}, {
    "first_name": "Dela",
    "last_name": "Josum",
    "email": "djosum9@ocn.ne.jp",
    "sex": "female",
    "blood_type": "A+",
    "address": "116 Sloan Park",
    "city": "Topeka",
    "state": "Kansas",
    "birthdate": "1972-10-16T07:00:55Z",
    "zipcode": "66629"
}, {
    "first_name": "Arvy",
    "last_name": "Bowler",
    "email": "abowlera@google.ru",
    "sex": "female",
    "blood_type": "O+",
    "address": "45083 La Follette Circle",
    "city": "New York City",
    "state": "New York",
    "birthdate": "1986-06-23T21:23:17Z",
    "zipcode": "10004"
}, {
    "first_name": "Etienne",
    "last_name": "Agirre",
    "email": "eagirreb@myspace.com",
    "sex": "female",
    "blood_type": "AB+",
    "address": "19754 Cascade Court",
    "city": "Sacramento",
    "state": "California",
    "birthdate": "1954-02-02T16:36:06Z",
    "zipcode": "94297"
}];

const visits = [{
    "visit_time": "2022-07-04T17:36:46Z",
    "administration_location": "inhome",
    "location_address": "8366 Browning Place",
    "location_city": "Arlington",
    "location_state": "Virginia",
    "location_zipcode": "22205",
    "administering_nurse": "Buddy Chue",
    "medication": "HeadacheEaser",
    "visit_duration_seconds": 1790,
    "medication_tolerance": 3,
    "blood_pressure": "118/76",
    "heartrate_bpm": 66,
    "pain_level": 1
}, {
    "visit_time": "2021-10-02T23:04:59Z",
    "administration_location": "inhome",
    "location_address": "13 Mallory Avenue",
    "location_city": "Wilmington",
    "location_state": "Delaware",
    "location_zipcode": "19892",
    "administering_nurse": "Teresa Sewill",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 1278,
    "medication_tolerance": 4,
    "blood_pressure": "126/76",
    "heartrate_bpm": 60,
    "pain_level": 5
}, {
    "visit_time": "2023-08-22T19:22:04Z",
    "administration_location": "hospital",
    "location_address": "8 Talmadge Pass",
    "location_city": "Farmington",
    "location_state": "Michigan",
    "location_zipcode": "48335",
    "administering_nurse": "Rebekkah Pedel",
    "medication": "PainReliefol",
    "visit_duration_seconds": 12410,
    "medication_tolerance": 4,
    "blood_pressure": "128/70",
    "heartrate_bpm": 69,
    "pain_level": 3
}, {
    "visit_time": "2023-02-01T16:40:33Z",
    "administration_location": "inhome",
    "location_address": "23249 Walton Avenue",
    "location_city": "Scottsdale",
    "location_state": "Arizona",
    "location_zipcode": "85260",
    "administering_nurse": "Quinn MacMorland",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 1507,
    "medication_tolerance": 5,
    "blood_pressure": "140/90",
    "heartrate_bpm": 79,
    "pain_level": 1
}, {
    "visit_time": "2022-03-16T22:02:37Z",
    "administration_location": "inhome",
    "location_address": "682 6th Trail",
    "location_city": "Las Vegas",
    "location_state": "Nevada",
    "location_zipcode": "89166",
    "administering_nurse": "Liliane Marrow",
    "medication": "SleepEZapam",
    "visit_duration_seconds": 14777,
    "medication_tolerance": 2,
    "blood_pressure": "142/88",
    "heartrate_bpm": 64,
    "pain_level": 7
}, {
    "visit_time": "2022-12-25T12:03:58Z",
    "administration_location": "inhome",
    "location_address": "0 Manley Trail",
    "location_city": "Atlanta",
    "location_state": "Georgia",
    "location_zipcode": "30340",
    "administering_nurse": "Queenie Lantoph",
    "medication": "ArthriFlex",
    "visit_duration_seconds": 14129,
    "medication_tolerance": 2,
    "blood_pressure": "132/88",
    "heartrate_bpm": 134,
    "pain_level": 3
}, {
    "visit_time": "2022-03-28T07:23:07Z",
    "administration_location": "inhome",
    "location_address": "137 Stoughton Avenue",
    "location_city": "Ann Arbor",
    "location_state": "Michigan",
    "location_zipcode": "48107",
    "administering_nurse": "Jackquelin Dale",
    "medication": "BloodPressureX",
    "visit_duration_seconds": 10760,
    "medication_tolerance": 3,
    "blood_pressure": "118/84",
    "heartrate_bpm": 131,
    "pain_level": 4
}, {
    "visit_time": "2023-03-11T18:02:19Z",
    "administration_location": "hospital",
    "location_address": "60271 Arapahoe Circle",
    "location_city": "Hyattsville",
    "location_state": "Maryland",
    "location_zipcode": "20784",
    "administering_nurse": "Moselle Kitchinghan",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 14523,
    "medication_tolerance": 4,
    "blood_pressure": "112/76",
    "heartrate_bpm": 79,
    "pain_level": 1
}, {
    "visit_time": "2022-11-18T23:26:00Z",
    "administration_location": "inhome",
    "location_address": "6 Acker Crossing",
    "location_city": "Las Vegas",
    "location_state": "Nevada",
    "location_zipcode": "89193",
    "administering_nurse": "Kristofer Burbank",
    "medication": "PainReliefol",
    "visit_duration_seconds": 5077,
    "medication_tolerance": 3,
    "blood_pressure": "115/72",
    "heartrate_bpm": 121,
    "pain_level": 1
}, {
    "visit_time": "2023-01-02T04:01:35Z",
    "administration_location": "inhome",
    "location_address": "359 Union Street",
    "location_city": "Hartford",
    "location_state": "Connecticut",
    "location_zipcode": "06152",
    "administering_nurse": "Cosmo Woollam",
    "medication": "SinusSoothe",
    "visit_duration_seconds": 2613,
    "medication_tolerance": 2,
    "blood_pressure": "125/85",
    "heartrate_bpm": 75,
    "pain_level": 8
}, {
    "visit_time": "2022-09-14T00:33:08Z",
    "administration_location": "hospital",
    "location_address": "343 Dwight Road",
    "location_city": "New Orleans",
    "location_state": "Louisiana",
    "location_zipcode": "70160",
    "administering_nurse": "Elke Basile",
    "medication": "MuscleMender",
    "visit_duration_seconds": 11107,
    "medication_tolerance": 1,
    "blood_pressure": "118/76",
    "heartrate_bpm": 73,
    "pain_level": 1
}, {
    "visit_time": "2021-02-14T21:08:32Z",
    "administration_location": "inhome",
    "location_address": "85 Manley Point",
    "location_city": "Erie",
    "location_state": "Pennsylvania",
    "location_zipcode": "16550",
    "administering_nurse": "Edgardo Tidmas",
    "medication": "SinusSoothe",
    "visit_duration_seconds": 12765,
    "medication_tolerance": 4,
    "blood_pressure": "118/84",
    "heartrate_bpm": 131,
    "pain_level": 1
}, {
    "visit_time": "2021-05-22T04:28:05Z",
    "administration_location": "hospital",
    "location_address": "22 Bobwhite Drive",
    "location_city": "Apache Junction",
    "location_state": "Arizona",
    "location_zipcode": "85219",
    "administering_nurse": "Ivar Look",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 3427,
    "medication_tolerance": 1,
    "blood_pressure": "132/78",
    "heartrate_bpm": 69,
    "pain_level": 2
}, {
    "visit_time": "2023-05-10T13:28:12Z",
    "administration_location": "inhome",
    "location_address": "918 Blue Bill Park Parkway",
    "location_city": "Clearwater",
    "location_state": "Florida",
    "location_zipcode": "33758",
    "administering_nurse": "Egbert Gately",
    "medication": "PainReliefol",
    "visit_duration_seconds": 5057,
    "medication_tolerance": 4,
    "blood_pressure": "130/79",
    "heartrate_bpm": 88,
    "pain_level": 10
}, {
    "visit_time": "2021-10-10T01:03:26Z",
    "administration_location": "hospital",
    "location_address": "1 Anhalt Park",
    "location_city": "Tampa",
    "location_state": "Florida",
    "location_zipcode": "33625",
    "administering_nurse": "Moll Hebblewaite",
    "medication": "VisionClarity",
    "visit_duration_seconds": 2354,
    "medication_tolerance": 2,
    "blood_pressure": "134/82",
    "heartrate_bpm": 103,
    "pain_level": 8
}, {
    "visit_time": "2022-01-25T13:36:05Z",
    "administration_location": "inhome",
    "location_address": "5839 Melby Hill",
    "location_city": "Milwaukee",
    "location_state": "Wisconsin",
    "location_zipcode": "53285",
    "administering_nurse": "Benita Le Gall",
    "medication": "ArthriFlex",
    "visit_duration_seconds": 11790,
    "medication_tolerance": 2,
    "blood_pressure": "128/70",
    "heartrate_bpm": 110,
    "pain_level": 6
}, {
    "visit_time": "2023-11-25T19:16:26Z",
    "administration_location": "inhome",
    "location_address": "58816 Corben Point",
    "location_city": "Pensacola",
    "location_state": "Florida",
    "location_zipcode": "32590",
    "administering_nurse": "George Osinin",
    "medication": "SinusSoothe",
    "visit_duration_seconds": 11903,
    "medication_tolerance": 2,
    "blood_pressure": "120/86",
    "heartrate_bpm": 138,
    "pain_level": 7
}, {
    "visit_time": "2021-05-21T17:32:29Z",
    "administration_location": "inhome",
    "location_address": "066 Hooker Street",
    "location_city": "Alexandria",
    "location_state": "Virginia",
    "location_zipcode": "22313",
    "administering_nurse": "Shir Cerro",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 7439,
    "medication_tolerance": 4,
    "blood_pressure": "128/74",
    "heartrate_bpm": 132,
    "pain_level": 7
}, {
    "visit_time": "2023-12-18T01:45:13Z",
    "administration_location": "hospital",
    "location_address": "19 New Castle Hill",
    "location_city": "Cleveland",
    "location_state": "Ohio",
    "location_zipcode": "44177",
    "administering_nurse": "Susana Newton",
    "medication": "AsthmaEase",
    "visit_duration_seconds": 1337,
    "medication_tolerance": 2,
    "blood_pressure": "134/80",
    "heartrate_bpm": 110,
    "pain_level": 8
}, {
    "visit_time": "2022-09-22T23:18:18Z",
    "administration_location": "inhome",
    "location_address": "58 Sunnyside Point",
    "location_city": "Springfield",
    "location_state": "Massachusetts",
    "location_zipcode": "01129",
    "administering_nurse": "Ermin Zollner",
    "medication": "VisionClarity",
    "visit_duration_seconds": 8576,
    "medication_tolerance": 1,
    "blood_pressure": "115/74",
    "heartrate_bpm": 117,
    "pain_level": 9
}, {
    "visit_time": "2021-10-09T22:30:46Z",
    "administration_location": "hospital",
    "location_address": "46694 Bashford Crossing",
    "location_city": "Portland",
    "location_state": "Oregon",
    "location_zipcode": "97211",
    "administering_nurse": "Irma Allcock",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 7556,
    "medication_tolerance": 2,
    "blood_pressure": "140/84",
    "heartrate_bpm": 118,
    "pain_level": 10
}, {
    "visit_time": "2021-07-11T19:46:26Z",
    "administration_location": "inhome",
    "location_address": "966 Montana Junction",
    "location_city": "Gainesville",
    "location_state": "Georgia",
    "location_zipcode": "30506",
    "administering_nurse": "Goraud Brushneen",
    "medication": "MoodStabilix",
    "visit_duration_seconds": 4735,
    "medication_tolerance": 4,
    "blood_pressure": "136/72",
    "heartrate_bpm": 64,
    "pain_level": 9
}, {
    "visit_time": "2022-05-13T09:02:15Z",
    "administration_location": "hospital",
    "location_address": "4 Upham Place",
    "location_city": "Bakersfield",
    "location_state": "California",
    "location_zipcode": "93399",
    "administering_nurse": "Sloane Sirmon",
    "medication": "BloodPressureX",
    "visit_duration_seconds": 11976,
    "medication_tolerance": 1,
    "blood_pressure": "144/92",
    "heartrate_bpm": 77,
    "pain_level": 2
}, {
    "visit_time": "2021-01-19T13:43:18Z",
    "administration_location": "hospital",
    "location_address": "2 Manufacturers Crossing",
    "location_city": "Austin",
    "location_state": "Texas",
    "location_zipcode": "78710",
    "administering_nurse": "Suzy McChruiter",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 13254,
    "medication_tolerance": 1,
    "blood_pressure": "134/84",
    "heartrate_bpm": 69,
    "pain_level": 6
}, {
    "visit_time": "2021-03-07T12:12:45Z",
    "administration_location": "hospital",
    "location_address": "0 Corscot Trail",
    "location_city": "Atlanta",
    "location_state": "Georgia",
    "location_zipcode": "31119",
    "administering_nurse": "Marchall Alejandre",
    "medication": "MuscleMender",
    "visit_duration_seconds": 1725,
    "medication_tolerance": 5,
    "blood_pressure": "134/90",
    "heartrate_bpm": 108,
    "pain_level": 7
}, {
    "visit_time": "2023-11-05T10:36:25Z",
    "administration_location": "inhome",
    "location_address": "71784 Milwaukee Street",
    "location_city": "Odessa",
    "location_state": "Texas",
    "location_zipcode": "79769",
    "administering_nurse": "Brynne Pedrol",
    "medication": "MuscleMender",
    "visit_duration_seconds": 6564,
    "medication_tolerance": 5,
    "blood_pressure": "136/80",
    "heartrate_bpm": 92,
    "pain_level": 10
}, {
    "visit_time": "2021-11-08T10:45:25Z",
    "administration_location": "hospital",
    "location_address": "822 West Place",
    "location_city": "Fresno",
    "location_state": "California",
    "location_zipcode": "93786",
    "administering_nurse": "Perren Bodle",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 8606,
    "medication_tolerance": 1,
    "blood_pressure": "134/80",
    "heartrate_bpm": 89,
    "pain_level": 4
}, {
    "visit_time": "2022-05-12T10:43:19Z",
    "administration_location": "hospital",
    "location_address": "10037 Burning Wood Circle",
    "location_city": "Akron",
    "location_state": "Ohio",
    "location_zipcode": "44305",
    "administering_nurse": "Angeli Jouhandeau",
    "medication": "DiabetiCare",
    "visit_duration_seconds": 10026,
    "medication_tolerance": 4,
    "blood_pressure": "125/72",
    "heartrate_bpm": 80,
    "pain_level": 1
}, {
    "visit_time": "2022-08-02T15:05:30Z",
    "administration_location": "inhome",
    "location_address": "29 Scott Terrace",
    "location_city": "Denver",
    "location_state": "Colorado",
    "location_zipcode": "80270",
    "administering_nurse": "Dodie Larwood",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 2596,
    "medication_tolerance": 1,
    "blood_pressure": "112/78",
    "heartrate_bpm": 135,
    "pain_level": 10
}, {
    "visit_time": "2021-03-21T01:02:10Z",
    "administration_location": "inhome",
    "location_address": "2 Dennis Place",
    "location_city": "Pomona",
    "location_state": "California",
    "location_zipcode": "91797",
    "administering_nurse": "Roseanna Flye",
    "medication": "HeartGuardia",
    "visit_duration_seconds": 1619,
    "medication_tolerance": 4,
    "blood_pressure": "115/72",
    "heartrate_bpm": 111,
    "pain_level": 1
}, {
    "visit_time": "2021-11-29T11:40:19Z",
    "administration_location": "hospital",
    "location_address": "87 Jenna Drive",
    "location_city": "Detroit",
    "location_state": "Michigan",
    "location_zipcode": "48217",
    "administering_nurse": "Jim Barber",
    "medication": "Medifloxin",
    "visit_duration_seconds": 11710,
    "medication_tolerance": 1,
    "blood_pressure": "120/75",
    "heartrate_bpm": 67,
    "pain_level": 1
}, {
    "visit_time": "2023-06-27T01:45:38Z",
    "administration_location": "hospital",
    "location_address": "483 Grim Place",
    "location_city": "Watertown",
    "location_state": "Massachusetts",
    "location_zipcode": "02472",
    "administering_nurse": "Meara McLenahan",
    "medication": "DigestiPro",
    "visit_duration_seconds": 2452,
    "medication_tolerance": 5,
    "blood_pressure": "140/80",
    "heartrate_bpm": 94,
    "pain_level": 3
}, {
    "visit_time": "2021-12-04T05:34:47Z",
    "administration_location": "hospital",
    "location_address": "237 Blue Bill Park Terrace",
    "location_city": "Springfield",
    "location_state": "Ohio",
    "location_zipcode": "45505",
    "administering_nurse": "Merrilee Melledy",
    "medication": "SkinSaverol",
    "visit_duration_seconds": 10345,
    "medication_tolerance": 5,
    "blood_pressure": "124/70",
    "heartrate_bpm": 122,
    "pain_level": 10
}, {
    "visit_time": "2022-06-20T10:20:59Z",
    "administration_location": "inhome",
    "location_address": "1382 Sloan Point",
    "location_city": "Miami",
    "location_state": "Florida",
    "location_zipcode": "33245",
    "administering_nurse": "Mira Dupree",
    "medication": "SkinSaverol",
    "visit_duration_seconds": 10779,
    "medication_tolerance": 1,
    "blood_pressure": "136/78",
    "heartrate_bpm": 107,
    "pain_level": 7
}, {
    "visit_time": "2021-12-27T15:28:50Z",
    "administration_location": "inhome",
    "location_address": "921 Ryan Circle",
    "location_city": "Zephyrhills",
    "location_state": "Florida",
    "location_zipcode": "33543",
    "administering_nurse": "Elsi Fakes",
    "medication": "HeadacheEaser",
    "visit_duration_seconds": 1570,
    "medication_tolerance": 4,
    "blood_pressure": "119/78",
    "heartrate_bpm": 129,
    "pain_level": 2
}, {
    "visit_time": "2021-05-12T13:39:59Z",
    "administration_location": "inhome",
    "location_address": "71 Merry Avenue",
    "location_city": "Stamford",
    "location_state": "Connecticut",
    "location_zipcode": "06912",
    "administering_nurse": "Ludovika Lightfoot",
    "medication": "HeartGuardia",
    "visit_duration_seconds": 7261,
    "medication_tolerance": 3,
    "blood_pressure": "125/80",
    "heartrate_bpm": 108,
    "pain_level": 5
}, {
    "visit_time": "2023-02-16T08:13:26Z",
    "administration_location": "hospital",
    "location_address": "9799 Lawn Court",
    "location_city": "Reston",
    "location_state": "Virginia",
    "location_zipcode": "20195",
    "administering_nurse": "Meaghan Walklot",
    "medication": "HeadacheEaser",
    "visit_duration_seconds": 1605,
    "medication_tolerance": 2,
    "blood_pressure": "118/80",
    "heartrate_bpm": 81,
    "pain_level": 3
}, {
    "visit_time": "2022-03-31T11:43:37Z",
    "administration_location": "hospital",
    "location_address": "32 Brentwood Point",
    "location_city": "Fresno",
    "location_state": "California",
    "location_zipcode": "93778",
    "administering_nurse": "Lettie Pie",
    "medication": "MuscleMender",
    "visit_duration_seconds": 9607,
    "medication_tolerance": 4,
    "blood_pressure": "134/86",
    "heartrate_bpm": 86,
    "pain_level": 10
}, {
    "visit_time": "2022-05-10T02:55:46Z",
    "administration_location": "hospital",
    "location_address": "55615 Nevada Crossing",
    "location_city": "Austin",
    "location_state": "Texas",
    "location_zipcode": "78744",
    "administering_nurse": "Giulia Block",
    "medication": "ImmunoBoost",
    "visit_duration_seconds": 6628,
    "medication_tolerance": 2,
    "blood_pressure": "128/88",
    "heartrate_bpm": 112,
    "pain_level": 10
}, {
    "visit_time": "2021-09-13T21:17:18Z",
    "administration_location": "hospital",
    "location_address": "24 1st Point",
    "location_city": "New York City",
    "location_state": "New York",
    "location_zipcode": "10039",
    "administering_nurse": "Salaidh Aldhous",
    "medication": "SleepEZapam",
    "visit_duration_seconds": 7659,
    "medication_tolerance": 1,
    "blood_pressure": "130/79",
    "heartrate_bpm": 76,
    "pain_level": 6
}, {
    "visit_time": "2021-01-15T03:57:05Z",
    "administration_location": "inhome",
    "location_address": "714 Canary Way",
    "location_city": "Washington",
    "location_state": "District of Columbia",
    "location_zipcode": "20078",
    "administering_nurse": "Cecilla Kemer",
    "medication": "PainReliefol",
    "visit_duration_seconds": 13295,
    "medication_tolerance": 1,
    "blood_pressure": "126/78",
    "heartrate_bpm": 105,
    "pain_level": 8
}, {
    "visit_time": "2021-10-05T18:34:20Z",
    "administration_location": "hospital",
    "location_address": "879 Ilene Junction",
    "location_city": "Columbia",
    "location_state": "South Carolina",
    "location_zipcode": "29203",
    "administering_nurse": "Thia Inman",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 1030,
    "medication_tolerance": 1,
    "blood_pressure": "125/78",
    "heartrate_bpm": 89,
    "pain_level": 1
}, {
    "visit_time": "2021-12-31T14:00:18Z",
    "administration_location": "inhome",
    "location_address": "2587 Bluestem Place",
    "location_city": "Tulsa",
    "location_state": "Oklahoma",
    "location_zipcode": "74126",
    "administering_nurse": "Matteo Radband",
    "medication": "HeadacheEaser",
    "visit_duration_seconds": 12227,
    "medication_tolerance": 4,
    "blood_pressure": "138/78",
    "heartrate_bpm": 137,
    "pain_level": 4
}, {
    "visit_time": "2022-04-26T17:34:20Z",
    "administration_location": "inhome",
    "location_address": "2261 Blue Bill Park Junction",
    "location_city": "Fresno",
    "location_state": "California",
    "location_zipcode": "93709",
    "administering_nurse": "Ericka Spears",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 2393,
    "medication_tolerance": 4,
    "blood_pressure": "144/90",
    "heartrate_bpm": 61,
    "pain_level": 1
}, {
    "visit_time": "2023-07-10T10:51:40Z",
    "administration_location": "hospital",
    "location_address": "863 Pond Trail",
    "location_city": "South Bend",
    "location_state": "Indiana",
    "location_zipcode": "46620",
    "administering_nurse": "Steve Ryce",
    "medication": "SinusSoothe",
    "visit_duration_seconds": 11807,
    "medication_tolerance": 3,
    "blood_pressure": "138/92",
    "heartrate_bpm": 81,
    "pain_level": 2
}, {
    "visit_time": "2021-12-31T23:23:57Z",
    "administration_location": "inhome",
    "location_address": "7682 Knutson Avenue",
    "location_city": "Seattle",
    "location_state": "Washington",
    "location_zipcode": "98133",
    "administering_nurse": "Parnell Giffaut",
    "medication": "ArthriFlex",
    "visit_duration_seconds": 3776,
    "medication_tolerance": 4,
    "blood_pressure": "118/72",
    "heartrate_bpm": 134,
    "pain_level": 8
}, {
    "visit_time": "2020-12-25T18:07:31Z",
    "administration_location": "inhome",
    "location_address": "5649 Anderson Plaza",
    "location_city": "Washington",
    "location_state": "District of Columbia",
    "location_zipcode": "20414",
    "administering_nurse": "Gabriella Rannald",
    "medication": "PainReliefol",
    "visit_duration_seconds": 6083,
    "medication_tolerance": 5,
    "blood_pressure": "120/78",
    "heartrate_bpm": 69,
    "pain_level": 7
}, {
    "visit_time": "2022-12-22T13:52:15Z",
    "administration_location": "hospital",
    "location_address": "3 Londonderry Alley",
    "location_city": "Omaha",
    "location_state": "Nebraska",
    "location_zipcode": "68124",
    "administering_nurse": "Maudie Smeed",
    "medication": "SkinSaverol",
    "visit_duration_seconds": 9257,
    "medication_tolerance": 1,
    "blood_pressure": "138/85",
    "heartrate_bpm": 136,
    "pain_level": 7
}, {
    "visit_time": "2022-01-23T18:33:03Z",
    "administration_location": "hospital",
    "location_address": "07 Steensland Place",
    "location_city": "Pasadena",
    "location_state": "Texas",
    "location_zipcode": "77505",
    "administering_nurse": "Alessandro Sandwith",
    "medication": "MuscleMender",
    "visit_duration_seconds": 7874,
    "medication_tolerance": 5,
    "blood_pressure": "115/76",
    "heartrate_bpm": 105,
    "pain_level": 9
}, {
    "visit_time": "2022-05-23T08:17:45Z",
    "administration_location": "hospital",
    "location_address": "49 Lunder Drive",
    "location_city": "Dallas",
    "location_state": "Texas",
    "location_zipcode": "75236",
    "administering_nurse": "Waverly Piscopo",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 1362,
    "medication_tolerance": 1,
    "blood_pressure": "126/76",
    "heartrate_bpm": 112,
    "pain_level": 10
}, {
    "visit_time": "2021-05-31T19:38:50Z",
    "administration_location": "inhome",
    "location_address": "2 Westport Street",
    "location_city": "Phoenix",
    "location_state": "Arizona",
    "location_zipcode": "85035",
    "administering_nurse": "Terry Roskrug",
    "medication": "SkinSaverol",
    "visit_duration_seconds": 3566,
    "medication_tolerance": 3,
    "blood_pressure": "144/92",
    "heartrate_bpm": 107,
    "pain_level": 1
}, {
    "visit_time": "2023-03-26T16:22:39Z",
    "administration_location": "inhome",
    "location_address": "3019 Spaight Place",
    "location_city": "New York City",
    "location_state": "New York",
    "location_zipcode": "10110",
    "administering_nurse": "Darnell Davidsson",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 10959,
    "medication_tolerance": 3,
    "blood_pressure": "128/78",
    "heartrate_bpm": 68,
    "pain_level": 3
}, {
    "visit_time": "2021-05-20T03:37:08Z",
    "administration_location": "hospital",
    "location_address": "4528 Hovde Point",
    "location_city": "Memphis",
    "location_state": "Tennessee",
    "location_zipcode": "38126",
    "administering_nurse": "Pierette Moughtin",
    "medication": "AsthmaEase",
    "visit_duration_seconds": 8509,
    "medication_tolerance": 5,
    "blood_pressure": "128/78",
    "heartrate_bpm": 120,
    "pain_level": 8
}, {
    "visit_time": "2021-06-24T13:30:36Z",
    "administration_location": "hospital",
    "location_address": "709 Annamark Avenue",
    "location_city": "Saint Petersburg",
    "location_state": "Florida",
    "location_zipcode": "33731",
    "administering_nurse": "Allan Steanson",
    "medication": "HeartGuardia",
    "visit_duration_seconds": 13501,
    "medication_tolerance": 3,
    "blood_pressure": "130/82",
    "heartrate_bpm": 114,
    "pain_level": 9
}, {
    "visit_time": "2021-02-18T21:23:06Z",
    "administration_location": "hospital",
    "location_address": "0 Corscot Court",
    "location_city": "Bellevue",
    "location_state": "Washington",
    "location_zipcode": "98008",
    "administering_nurse": "Barry McCutheon",
    "medication": "Medifloxin",
    "visit_duration_seconds": 8403,
    "medication_tolerance": 2,
    "blood_pressure": "140/80",
    "heartrate_bpm": 114,
    "pain_level": 3
}, {
    "visit_time": "2021-09-19T15:23:27Z",
    "administration_location": "hospital",
    "location_address": "3 Kinsman Parkway",
    "location_city": "Arlington",
    "location_state": "Texas",
    "location_zipcode": "76011",
    "administering_nurse": "Tomlin Cossins",
    "medication": "MoodStabilix",
    "visit_duration_seconds": 12075,
    "medication_tolerance": 5,
    "blood_pressure": "144/92",
    "heartrate_bpm": 137,
    "pain_level": 8
}, {
    "visit_time": "2022-10-06T06:15:15Z",
    "administration_location": "hospital",
    "location_address": "8 Sauthoff Center",
    "location_city": "Honolulu",
    "location_state": "Hawaii",
    "location_zipcode": "96805",
    "administering_nurse": "Arvy Cana",
    "medication": "ArthriFlex",
    "visit_duration_seconds": 3588,
    "medication_tolerance": 4,
    "blood_pressure": "138/70",
    "heartrate_bpm": 91,
    "pain_level": 3
}, {
    "visit_time": "2023-11-09T04:08:29Z",
    "administration_location": "inhome",
    "location_address": "4870 Onsgard Avenue",
    "location_city": "Greensboro",
    "location_state": "North Carolina",
    "location_zipcode": "27425",
    "administering_nurse": "Benni Gratton",
    "medication": "VisionClarity",
    "visit_duration_seconds": 1549,
    "medication_tolerance": 2,
    "blood_pressure": "122/78",
    "heartrate_bpm": 97,
    "pain_level": 6
}, {
    "visit_time": "2021-04-03T19:25:14Z",
    "administration_location": "inhome",
    "location_address": "48 East Hill",
    "location_city": "Odessa",
    "location_state": "Texas",
    "location_zipcode": "79764",
    "administering_nurse": "Rocky Cubin",
    "medication": "DigestiPro",
    "visit_duration_seconds": 13362,
    "medication_tolerance": 4,
    "blood_pressure": "124/76",
    "heartrate_bpm": 119,
    "pain_level": 10
}, {
    "visit_time": "2023-06-21T22:32:23Z",
    "administration_location": "inhome",
    "location_address": "25240 Union Pass",
    "location_city": "Topeka",
    "location_state": "Kansas",
    "location_zipcode": "66611",
    "administering_nurse": "Delaney McCrorie",
    "medication": "PainReliefol",
    "visit_duration_seconds": 9913,
    "medication_tolerance": 1,
    "blood_pressure": "130/70",
    "heartrate_bpm": 105,
    "pain_level": 4
}, {
    "visit_time": "2021-10-22T19:07:19Z",
    "administration_location": "inhome",
    "location_address": "482 Chive Alley",
    "location_city": "Santa Rosa",
    "location_state": "California",
    "location_zipcode": "95405",
    "administering_nurse": "Garrik Kettridge",
    "medication": "Medifloxin",
    "visit_duration_seconds": 9929,
    "medication_tolerance": 3,
    "blood_pressure": "112/76",
    "heartrate_bpm": 80,
    "pain_level": 5
}, {
    "visit_time": "2022-08-12T11:25:26Z",
    "administration_location": "inhome",
    "location_address": "79 Melby Hill",
    "location_city": "Birmingham",
    "location_state": "Alabama",
    "location_zipcode": "35220",
    "administering_nurse": "Virgie Lyffe",
    "medication": "SleepEZapam",
    "visit_duration_seconds": 4305,
    "medication_tolerance": 2,
    "blood_pressure": "142/82",
    "heartrate_bpm": 98,
    "pain_level": 1
}, {
    "visit_time": "2022-11-14T19:28:51Z",
    "administration_location": "inhome",
    "location_address": "5984 Sycamore Crossing",
    "location_city": "Gulfport",
    "location_state": "Mississippi",
    "location_zipcode": "39505",
    "administering_nurse": "Jannelle Purchon",
    "medication": "AllergiClear",
    "visit_duration_seconds": 7611,
    "medication_tolerance": 1,
    "blood_pressure": "140/88",
    "heartrate_bpm": 75,
    "pain_level": 6
}, {
    "visit_time": "2021-06-08T22:48:44Z",
    "administration_location": "inhome",
    "location_address": "16 Fairview Circle",
    "location_city": "Humble",
    "location_state": "Texas",
    "location_zipcode": "77346",
    "administering_nurse": "Catina Pendrigh",
    "medication": "MoodStabilix",
    "visit_duration_seconds": 13232,
    "medication_tolerance": 5,
    "blood_pressure": "119/78",
    "heartrate_bpm": 87,
    "pain_level": 7
}, {
    "visit_time": "2021-10-13T09:14:58Z",
    "administration_location": "inhome",
    "location_address": "88044 Chive Trail",
    "location_city": "Sterling",
    "location_state": "Virginia",
    "location_zipcode": "20167",
    "administering_nurse": "Mabelle Langham",
    "medication": "HeartGuardia",
    "visit_duration_seconds": 3609,
    "medication_tolerance": 2,
    "blood_pressure": "132/78",
    "heartrate_bpm": 95,
    "pain_level": 1
}, {
    "visit_time": "2022-03-12T22:19:09Z",
    "administration_location": "hospital",
    "location_address": "59 Nelson Parkway",
    "location_city": "Lancaster",
    "location_state": "Pennsylvania",
    "location_zipcode": "17622",
    "administering_nurse": "Harp Miguet",
    "medication": "BloodPressureX",
    "visit_duration_seconds": 3892,
    "medication_tolerance": 1,
    "blood_pressure": "115/76",
    "heartrate_bpm": 115,
    "pain_level": 9
}, {
    "visit_time": "2023-07-27T15:52:43Z",
    "administration_location": "inhome",
    "location_address": "6564 Oriole Crossing",
    "location_city": "Oklahoma City",
    "location_state": "Oklahoma",
    "location_zipcode": "73119",
    "administering_nurse": "Nathanil Berdale",
    "medication": "VisionClarity",
    "visit_duration_seconds": 11860,
    "medication_tolerance": 4,
    "blood_pressure": "126/78",
    "heartrate_bpm": 73,
    "pain_level": 8
}, {
    "visit_time": "2022-12-11T00:27:23Z",
    "administration_location": "inhome",
    "location_address": "07039 Reinke Junction",
    "location_city": "Saint Paul",
    "location_state": "Minnesota",
    "location_zipcode": "55166",
    "administering_nurse": "Em Hrycek",
    "medication": "AllergiClear",
    "visit_duration_seconds": 5297,
    "medication_tolerance": 3,
    "blood_pressure": "126/72",
    "heartrate_bpm": 138,
    "pain_level": 8
}, {
    "visit_time": "2021-10-28T07:41:32Z",
    "administration_location": "hospital",
    "location_address": "279 Crescent Oaks Court",
    "location_city": "Reno",
    "location_state": "Nevada",
    "location_zipcode": "89510",
    "administering_nurse": "Denys Lea",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 8103,
    "medication_tolerance": 1,
    "blood_pressure": "128/76",
    "heartrate_bpm": 70,
    "pain_level": 2
}, {
    "visit_time": "2022-12-08T08:14:27Z",
    "administration_location": "inhome",
    "location_address": "9 Lerdahl Pass",
    "location_city": "Harrisburg",
    "location_state": "Pennsylvania",
    "location_zipcode": "17140",
    "administering_nurse": "Eric Gatherell",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 11602,
    "medication_tolerance": 1,
    "blood_pressure": "134/82",
    "heartrate_bpm": 119,
    "pain_level": 4
}, {
    "visit_time": "2022-09-10T21:26:32Z",
    "administration_location": "inhome",
    "location_address": "068 Texas Plaza",
    "location_city": "Minneapolis",
    "location_state": "Minnesota",
    "location_zipcode": "55412",
    "administering_nurse": "Eddy Spedroni",
    "medication": "AllergiClear",
    "visit_duration_seconds": 7991,
    "medication_tolerance": 1,
    "blood_pressure": "140/80",
    "heartrate_bpm": 104,
    "pain_level": 3
}, {
    "visit_time": "2023-04-06T21:33:36Z",
    "administration_location": "hospital",
    "location_address": "5172 Sloan Avenue",
    "location_city": "Dayton",
    "location_state": "Ohio",
    "location_zipcode": "45432",
    "administering_nurse": "Jordana Bostock",
    "medication": "ImmunoBoost",
    "visit_duration_seconds": 1449,
    "medication_tolerance": 1,
    "blood_pressure": "134/86",
    "heartrate_bpm": 96,
    "pain_level": 2
}, {
    "visit_time": "2021-08-04T04:15:30Z",
    "administration_location": "hospital",
    "location_address": "79 Stoughton Circle",
    "location_city": "Lubbock",
    "location_state": "Texas",
    "location_zipcode": "79410",
    "administering_nurse": "Maryann Fryett",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 13684,
    "medication_tolerance": 3,
    "blood_pressure": "126/75",
    "heartrate_bpm": 110,
    "pain_level": 9
}, {
    "visit_time": "2023-07-14T07:25:14Z",
    "administration_location": "inhome",
    "location_address": "5069 Kedzie Trail",
    "location_city": "Long Beach",
    "location_state": "California",
    "location_zipcode": "90840",
    "administering_nurse": "Kahlil Sainteau",
    "medication": "ProbiotaMax",
    "visit_duration_seconds": 2979,
    "medication_tolerance": 1,
    "blood_pressure": "136/78",
    "heartrate_bpm": 129,
    "pain_level": 7
}, {
    "visit_time": "2023-09-28T08:14:30Z",
    "administration_location": "hospital",
    "location_address": "1090 South Trail",
    "location_city": "Brooklyn",
    "location_state": "New York",
    "location_zipcode": "11205",
    "administering_nurse": "Birk MacCartney",
    "medication": "Medifloxin",
    "visit_duration_seconds": 10811,
    "medication_tolerance": 4,
    "blood_pressure": "138/85",
    "heartrate_bpm": 98,
    "pain_level": 1
}, {
    "visit_time": "2022-06-25T14:28:30Z",
    "administration_location": "hospital",
    "location_address": "48 Mcbride Pass",
    "location_city": "Winston Salem",
    "location_state": "North Carolina",
    "location_zipcode": "27157",
    "administering_nurse": "Reidar Plowes",
    "medication": "HeartGuardia",
    "visit_duration_seconds": 7177,
    "medication_tolerance": 3,
    "blood_pressure": "136/78",
    "heartrate_bpm": 103,
    "pain_level": 8
}, {
    "visit_time": "2021-10-09T19:33:23Z",
    "administration_location": "inhome",
    "location_address": "77 Blue Bill Park Park",
    "location_city": "Sacramento",
    "location_state": "California",
    "location_zipcode": "94291",
    "administering_nurse": "Ebenezer Thistleton",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 1841,
    "medication_tolerance": 4,
    "blood_pressure": "120/86",
    "heartrate_bpm": 128,
    "pain_level": 7
}, {
    "visit_time": "2023-06-08T22:42:37Z",
    "administration_location": "inhome",
    "location_address": "630 Sugar Park",
    "location_city": "Oklahoma City",
    "location_state": "Oklahoma",
    "location_zipcode": "73119",
    "administering_nurse": "Oliviero Ubach",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 7339,
    "medication_tolerance": 4,
    "blood_pressure": "144/90",
    "heartrate_bpm": 108,
    "pain_level": 1
}, {
    "visit_time": "2023-10-16T00:01:27Z",
    "administration_location": "inhome",
    "location_address": "792 Del Sol Trail",
    "location_city": "Syracuse",
    "location_state": "New York",
    "location_zipcode": "13251",
    "administering_nurse": "Pearce Cunde",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 12915,
    "medication_tolerance": 3,
    "blood_pressure": "119/78",
    "heartrate_bpm": 137,
    "pain_level": 10
}, {
    "visit_time": "2022-10-28T05:34:44Z",
    "administration_location": "hospital",
    "location_address": "1 Dawn Park",
    "location_city": "Phoenix",
    "location_state": "Arizona",
    "location_zipcode": "85083",
    "administering_nurse": "Tybie Bartalot",
    "medication": "HeadacheEaser",
    "visit_duration_seconds": 9625,
    "medication_tolerance": 5,
    "blood_pressure": "136/86",
    "heartrate_bpm": 103,
    "pain_level": 4
}, {
    "visit_time": "2022-03-01T19:25:48Z",
    "administration_location": "inhome",
    "location_address": "271 Victoria Plaza",
    "location_city": "Austin",
    "location_state": "Texas",
    "location_zipcode": "78732",
    "administering_nurse": "Emeline Hurran",
    "medication": "CoughCalmix",
    "visit_duration_seconds": 7066,
    "medication_tolerance": 5,
    "blood_pressure": "112/70",
    "heartrate_bpm": 88,
    "pain_level": 7
}, {
    "visit_time": "2023-05-02T23:37:17Z",
    "administration_location": "inhome",
    "location_address": "338 Memorial Center",
    "location_city": "Pittsburgh",
    "location_state": "Pennsylvania",
    "location_zipcode": "15255",
    "administering_nurse": "Roseanne Rickcord",
    "medication": "DigestiPro",
    "visit_duration_seconds": 3981,
    "medication_tolerance": 4,
    "blood_pressure": "134/86",
    "heartrate_bpm": 127,
    "pain_level": 5
}, {
    "visit_time": "2021-02-12T20:45:02Z",
    "administration_location": "inhome",
    "location_address": "88 Dryden Pass",
    "location_city": "Erie",
    "location_state": "Pennsylvania",
    "location_zipcode": "16565",
    "administering_nurse": "Chet Sperling",
    "medication": "BloodPressureX",
    "visit_duration_seconds": 11024,
    "medication_tolerance": 1,
    "blood_pressure": "112/72",
    "heartrate_bpm": 98,
    "pain_level": 7
}, {
    "visit_time": "2021-01-05T01:37:25Z",
    "administration_location": "hospital",
    "location_address": "89 Erie Center",
    "location_city": "Virginia Beach",
    "location_state": "Virginia",
    "location_zipcode": "23459",
    "administering_nurse": "Audre Isaksen",
    "medication": "VisionClarity",
    "visit_duration_seconds": 12408,
    "medication_tolerance": 4,
    "blood_pressure": "130/82",
    "heartrate_bpm": 134,
    "pain_level": 9
}, {
    "visit_time": "2021-09-13T14:54:14Z",
    "administration_location": "inhome",
    "location_address": "6257 Loeprich Terrace",
    "location_city": "Montgomery",
    "location_state": "Alabama",
    "location_zipcode": "36134",
    "administering_nurse": "Kore Cracoe",
    "medication": "Medifloxin",
    "visit_duration_seconds": 13398,
    "medication_tolerance": 1,
    "blood_pressure": "128/88",
    "heartrate_bpm": 74,
    "pain_level": 8
}, {
    "visit_time": "2023-08-29T11:07:05Z",
    "administration_location": "inhome",
    "location_address": "96 Sugar Court",
    "location_city": "Philadelphia",
    "location_state": "Pennsylvania",
    "location_zipcode": "19109",
    "administering_nurse": "Evey Twiname",
    "medication": "ArthriFlex",
    "visit_duration_seconds": 7272,
    "medication_tolerance": 1,
    "blood_pressure": "118/72",
    "heartrate_bpm": 125,
    "pain_level": 7
}, {
    "visit_time": "2021-01-04T11:34:24Z",
    "administration_location": "hospital",
    "location_address": "09950 Marquette Pass",
    "location_city": "Huntington",
    "location_state": "West Virginia",
    "location_zipcode": "25770",
    "administering_nurse": "Aggy Sloane",
    "medication": "DigestiPro",
    "visit_duration_seconds": 2907,
    "medication_tolerance": 1,
    "blood_pressure": "124/78",
    "heartrate_bpm": 87,
    "pain_level": 6
}, {
    "visit_time": "2022-04-22T21:49:22Z",
    "administration_location": "hospital",
    "location_address": "46975 Burrows Hill",
    "location_city": "Charleston",
    "location_state": "West Virginia",
    "location_zipcode": "25389",
    "administering_nurse": "Ricardo Courtonne",
    "medication": "SkinSaverol",
    "visit_duration_seconds": 8277,
    "medication_tolerance": 4,
    "blood_pressure": "132/88",
    "heartrate_bpm": 98,
    "pain_level": 2
}, {
    "visit_time": "2022-12-05T21:09:27Z",
    "administration_location": "hospital",
    "location_address": "0882 Toban Junction",
    "location_city": "Lafayette",
    "location_state": "Louisiana",
    "location_zipcode": "70593",
    "administering_nurse": "Erhart Stronack",
    "medication": "BloodPressureX",
    "visit_duration_seconds": 13130,
    "medication_tolerance": 1,
    "blood_pressure": "124/88",
    "heartrate_bpm": 89,
    "pain_level": 6
}, {
    "visit_time": "2022-10-15T01:34:56Z",
    "administration_location": "inhome",
    "location_address": "770 South Avenue",
    "location_city": "Norfolk",
    "location_state": "Virginia",
    "location_zipcode": "23504",
    "administering_nurse": "Gradeigh Trahearn",
    "medication": "PainReliefol",
    "visit_duration_seconds": 4709,
    "medication_tolerance": 2,
    "blood_pressure": "112/70",
    "heartrate_bpm": 123,
    "pain_level": 4
}, {
    "visit_time": "2021-10-19T14:46:20Z",
    "administration_location": "inhome",
    "location_address": "736 Browning Trail",
    "location_city": "New York City",
    "location_state": "New York",
    "location_zipcode": "10280",
    "administering_nurse": "Alyosha Abramson",
    "medication": "PainReliefol",
    "visit_duration_seconds": 14367,
    "medication_tolerance": 4,
    "blood_pressure": "130/76",
    "heartrate_bpm": 73,
    "pain_level": 5
}, {
    "visit_time": "2022-05-04T17:47:44Z",
    "administration_location": "hospital",
    "location_address": "365 North Park",
    "location_city": "Cleveland",
    "location_state": "Ohio",
    "location_zipcode": "44111",
    "administering_nurse": "Ricca McCandie",
    "medication": "BloodPressureX",
    "visit_duration_seconds": 9349,
    "medication_tolerance": 5,
    "blood_pressure": "130/82",
    "heartrate_bpm": 114,
    "pain_level": 5
}, {
    "visit_time": "2023-11-21T21:12:02Z",
    "administration_location": "inhome",
    "location_address": "6263 Dakota Trail",
    "location_city": "Washington",
    "location_state": "District of Columbia",
    "location_zipcode": "20520",
    "administering_nurse": "Danya Start",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 4767,
    "medication_tolerance": 1,
    "blood_pressure": "118/84",
    "heartrate_bpm": 72,
    "pain_level": 7
}, {
    "visit_time": "2023-12-05T09:08:08Z",
    "administration_location": "inhome",
    "location_address": "02 West Hill",
    "location_city": "Toledo",
    "location_state": "Ohio",
    "location_zipcode": "43605",
    "administering_nurse": "Ernaline Fahy",
    "medication": "Medifloxin",
    "visit_duration_seconds": 8915,
    "medication_tolerance": 2,
    "blood_pressure": "128/88",
    "heartrate_bpm": 93,
    "pain_level": 6
}, {
    "visit_time": "2021-03-24T13:28:36Z",
    "administration_location": "inhome",
    "location_address": "3 Elmside Terrace",
    "location_city": "Stamford",
    "location_state": "Connecticut",
    "location_zipcode": "06912",
    "administering_nurse": "Kathie Storrar",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 7032,
    "medication_tolerance": 1,
    "blood_pressure": "138/85",
    "heartrate_bpm": 134,
    "pain_level": 1
}, {
    "visit_time": "2023-06-06T12:05:00Z",
    "administration_location": "hospital",
    "location_address": "5165 Manitowish Court",
    "location_city": "Seminole",
    "location_state": "Florida",
    "location_zipcode": "34642",
    "administering_nurse": "Hewe Dollman",
    "medication": "PainReliefol",
    "visit_duration_seconds": 6315,
    "medication_tolerance": 4,
    "blood_pressure": "138/92",
    "heartrate_bpm": 133,
    "pain_level": 4
}, {
    "visit_time": "2021-03-31T00:27:54Z",
    "administration_location": "inhome",
    "location_address": "48 3rd Alley",
    "location_city": "Atlanta",
    "location_state": "Georgia",
    "location_zipcode": "31132",
    "administering_nurse": "Hendrika Gareisr",
    "medication": "AllergiClear",
    "visit_duration_seconds": 12067,
    "medication_tolerance": 2,
    "blood_pressure": "125/85",
    "heartrate_bpm": 80,
    "pain_level": 9
}, {
    "visit_time": "2023-08-20T21:01:38Z",
    "administration_location": "hospital",
    "location_address": "189 Burrows Terrace",
    "location_city": "New York City",
    "location_state": "New York",
    "location_zipcode": "10131",
    "administering_nurse": "Natividad Skurm",
    "medication": "MoodStabilix",
    "visit_duration_seconds": 11512,
    "medication_tolerance": 1,
    "blood_pressure": "125/78",
    "heartrate_bpm": 94,
    "pain_level": 4
}, {
    "visit_time": "2023-05-11T17:43:37Z",
    "administration_location": "hospital",
    "location_address": "466 Clemons Street",
    "location_city": "Saint Louis",
    "location_state": "Missouri",
    "location_zipcode": "63158",
    "administering_nurse": "Egbert Down",
    "medication": "CholesterBlock",
    "visit_duration_seconds": 7698,
    "medication_tolerance": 1,
    "blood_pressure": "126/90",
    "heartrate_bpm": 79,
    "pain_level": 10
}, {
    "visit_time": "2022-11-15T13:33:12Z",
    "administration_location": "hospital",
    "location_address": "047 Crowley Point",
    "location_city": "San Diego",
    "location_state": "California",
    "location_zipcode": "92115",
    "administering_nurse": "Camila Brierley",
    "medication": "Medifloxin",
    "visit_duration_seconds": 12471,
    "medication_tolerance": 2,
    "blood_pressure": "126/75",
    "heartrate_bpm": 126,
    "pain_level": 8
}];

module.exports = {
    patients,
    visits
};